### ISSUE TITLE
Movable not working well on Android

### ISSUE THREAD

**Issue by nlshuynguyen** [wwimmo/react-native-sketch-image#23]
When I drag a shape sticker on Android, it moved very slow. But on IOS it work well. 
Video: https://drive.google.com/file/d/1nAVihZcn65irtK-OQkxq18cg2SNyeZ-5/view?usp=sharing
How can I fix it ?.
Thank you

**Comment by nlshuynguyen** [comment]
I had another question. Can we add fill color to shape not border ?

**Comment by creambyemute** [comment]
@nlshuynguyen 
I haven't watched the video. Did you test on device or emulator?

But in general, yes the Android Implementation is less performant and will start lagging when multiple shapes have been added, iOS will remain smooth.
I'm sure some improvements could be made to improve the Android performance.

To your second question, not that is not yet possible as it's not implemented.
Should be fairly easy to add though, so feel free to have a look at it and see check where it limits it to the path/border only.

**Comment by nlshuynguyen** [comment]
When call `addShape({ shapeType: 'Circle' })` in the first time, shape will move very slowly but call addShape again it will be ok.

**Comment by nlshuynguyen** [comment]
I went through code android. I change `Paint.Style.STROKE` to `Paint.Style.FILL` it will fill color the shape but I don't know how to implement that.

**Comment by creambyemute** [comment]
@nlshuynguyen To the first comment: Yeah I noticed this as well. The issue is in the part where the shape is created, the dimensions of the parent/canvas are wrong.

To the second comment: A boolean or and a function to change from Fill to stroke would be good I think.
