### ISSUE TITLE
Is there way to sketch over the shapes?

### ISSUE THREAD

**Issue by kamlesh1000** [wwimmo/react-native-sketch-image#27]
Thanks for the amazing work. The free sketch is drawing below the shapes of the border now. Can anyone guide me through to allow sketching above the shapes? Thanks.

**Comment by vladimirevstratov** [comment]
same issue

**Comment by creambyemute** [comment]
Hmm, probably rendering/drawing the shapes before the paths?

**Comment by creambyemute** [comment]
@kamlesh1000 @vladimirevstratov This repo is gonna be discontinued soon as it's not in use anymore. What you want to achieve would probably require drawing the free sketch before the shapes on the drawing methods of the iOS/Android implementation.

Closing this for now.
