### ISSUE TITLE
Publishing the repo to npm or yarn

### ISSUE THREAD

**Issue by Alex0jk** [wwimmo/react-native-sketch-image#31]
Hi, I've been checking the library and noticed that it seems that it isn't currently on npm or yarn. I am wondering if there are any plans to publish it there, as it would be very helpful for keeping track of the library and better than just adding it from Github.

**Comment by creambyemute** [comment]
@Alex0jk atm not no. Main reason is that we're planning to either replace it (in our app) or overhaul it (at least some parts).

But I do certainly agree that it would be better 👍 .
