### ISSUE TITLE
iOS - stroke ends prematurely

### ISSUE THREAD

**Issue by victormartingarcia** [wwimmo/react-native-sketch-image#32]
I'm having a glitch on iOS. As you can see in the video, the strokes are ending prematurely while drawing. 

This does not happen in Android. Any ideas on how to fix it? I am pretty sure there are no other gesture callbacks interfering

<img src="https://user-images.githubusercontent.com/659832/91653866-84b1c380-eaa4-11ea-9022-e7becfe0fd87.gif" width="200">

**Comment by isumesh** [comment]
@wwimmo-mf Any update ? Facing same issue ?

**Comment by gollobo** [comment]
Same issue here, only in iOS

**Comment by creambyemute** [comment]
@victormartingarcia @isumesh @gollobo If you don't need the shapes, have a look at https://github.com/creambyemute/react-native-sketch-canvas which is the original terrylinla implementation + 2 commits with fixes for iOS.

We're using that at the moment as we don't need the shapes anymore.
